export const COMM_CREATE = 'COMM_CREATE';
export const MASSDK_CREATE = 'MASSDK_CREATE';
export const MAP_CREATE = 'MAP_CREATE';
export const MASSROUTE_CREATE = 'MASSROUTE_CREATE';
export const MASSROUTEPRO_CREATE = 'MASSROUTEPRO_CREATE';
//export const COORDINATES_CREATE = 'COORDINATES_CREATE';
export const STATSAVE_CREATE = 'STATSAVE_CREATE';
//export const MASSPLAN_CREATE = 'MASSPLAN_CREATE';