export const MASSDK_CREATE = 'MASSDK_CREATE';
export const MASSROUTE_CREATE = 'MASSROUTE_CREATE';
export const MASSROUTEPRO_CREATE = 'MASSROUTEPRO_CREATE';
export const STATSAVE_CREATE = 'STATSAVE_CREATE';
